// AUTO-GENERATED from LifeInvader (EN3) Clothing_and_Vehicle_List.xlsx — 'Clothing List' sheet
// Bu dosya elle duzenlenmemelidir. Kaynak dosya guncellenince yeniden uretilmelidir.

export const CLOTHING = {
  "male": {
    "TOP/HOODIE": [
      "Air Bior pullover sweater",
      "Casual neon set",
      "Casual neon torso",
      "Chanel top",
      "Glowing Bomber Set NEW Sample LW",
      "Grand RP collection T-shirt",
      "Grand RP collection hoodie",
      "Hoodie with Balaclava Cap X Yazzy",
      "LM Playboy T-shirt with luminous print",
      "LM Playboy full set with luminous print",
      "LM Playboy jacket with luminous print",
      "LM Playboy sweatshirt with luminous print",
      "Lui Vi T-shirt",
      "Lui Vi full set",
      "Lui Vi jacket",
      "Lui Vi sweatshirt",
      "Lui Vi top",
      "Mikachu hoodie",
      "Muci Not Fake hoodie",
      "Muci hoodie",
      "Muci hoodie with snake",
      "Muci sweatshirt",
      "Niki new collection hoodie",
      "Niki tech top",
      "Niki track suit top",
      "Off-White sweatshirt",
      "Philip Plein T-shirt",
      "Social Club hoodie",
      "Ston Islan Classic Sportswear",
      "T-shirt of one-color CAP brand",
      "TRON full set",
      "TRON torso",
      "The West Pace jacket",
      "Tsum collection T-shirt",
      "UP-Green Sweatshirt",
      "Wide printed football T-shirt",
      "black jacket with yellow trim",
      "bomber jacket with glowing elements",
      "branded Molo T-shirt",
      "branded T-shirt",
      "branded insulated hoodie",
      "branded longsleeve",
      "bright hoodie",
      "collection 2022 T-shirt",
      "cropp collection T-shirt",
      "denim jacket",
      "fur coat without a hood",
      "haliky T-shirt",
      "haliky hoodie",
      "jacket with T-shirt",
      "jacket with luminous trim",
      "luminous T-shirt",
      "luminous jacket with turquoise trim",
      "mix collection T-shirt",
      "scary turtleneck T-shirt",
      "summer collection T-shirt",
      "trendy jacket",
      "vintage Abibas Olympic Jerseys"
    ],
    "PANTS": [
      "Abibas pants",
      "Abibas sport pants",
      "Abibas sweatpants",
      "Bior pants",
      "Casual neon pants",
      "Classic denim shorts",
      "Grand RP collection pants",
      "LM Playboy pants with luminous print",
      "Leather gothic pants",
      "Lui Vi pants",
      "Muci pants",
      "Muci trousers",
      "Neon Pants Set New Sample LW",
      "Niki new collection pants",
      "Niki tech fleece pants",
      "Niki track suit pants",
      "Shorts Lui Vi",
      "TRON pants",
      "bright trousers",
      "half-glowing pants",
      "insulated personal pants",
      "luminous Fendi pants",
      "luminous Grand RP trousers",
      "luminous trousers",
      "neon pants",
      "new fashionable joggers",
      "summer voyage shorts"
    ],
    "SHOES": [
      "Abibas Marquee Boost Lows shoes",
      "Abibas Pezy Boost 700 V3 Alvah shoes",
      "Abibas Pezy foam shoes",
      "Abibas Pro Bounce 2019 Lows shoes",
      "Acic Gel Kayano sneakers.",
      "Alastor McQueen Oversized sneakers",
      "Balenciaga Track sneakers",
      "Casual neon shoes",
      "Ground Mordan 4 Retro Laser 30th shoes",
      "Mordan 1 shoes",
      "Mordan 6 shoes",
      "Muci branded flip-flops",
      "Niki Groundporce One new collection shoes",
      "Niki Shox shoes",
      "Niki Uptempo shoes",
      "Niki Zoom Freak 1 Multi-Color shoes",
      "Off-White Pezy Boost shoes",
      "Off-White luminous Keezy Boost shoes",
      "Pans sneakers",
      "Pezy Boost shoes",
      "RGB neon shoes",
      "TRON shoes",
      "luminous Keezy Boost shoes",
      "luminous shoes",
      "neon shoes",
      "rare luminous shoes",
      "red sneakers"
    ],
    "ACCESSORY": [
      "Cyberpunk greatsword accessory",
      "Grand Chain",
      "Satanic Wings",
      "Snake around the body accessory",
      "Unicorn Wings",
      "boxing gloves",
      "chain around the body accessory",
      "chain lost treasure neon accessory",
      "deer antler accessory",
      "deer antlers with a red nose accessory",
      "flying bear on the shoulder accessory",
      "gloves",
      "glowing snow glasses",
      "hearts Pride glasses",
      "neck scarf accessory",
      "pixel glasses",
      "shiny deer antler headband accessory",
      "snowflake glasses",
      "wristband accessory"
    ],
    "MASKS": [
      "Bigness mask",
      "Casual neon helmet",
      "Christmas tree mask",
      "Cupids crown",
      "Daft Punk mask",
      "Glowing face scarf mask",
      "Jason blue mask",
      "LM Playboy mask with luminous print",
      "Lui Vi desert scarf mask",
      "Munk mask",
      "Nik mask",
      "Pot and pan on head",
      "Razer headphones",
      "Santa Claus mask",
      "Saruko neon mask",
      "Sashmello mask",
      "Satanic horns",
      "TRON helmet",
      "TV-head mask",
      "alien with neon eyes mask",
      "anime mask",
      "bandana mask",
      "baseball mask",
      "boxing helmet",
      "carnival mask",
      "clown mask",
      "cowgirl hat",
      "demon mask",
      "desert scarf mask",
      "devil mask",
      "earphones with a heart",
      "emoji mask",
      "evil mask",
      "exotic mask",
      "fox mask",
      "gorilla mask",
      "handkerchief mask",
      "kitsune mask",
      "luminous head bag mask",
      "monkey boss mask",
      "owl mask",
      "panama hat",
      "penguin mask",
      "pig mask",
      "purge mask",
      "raccoon mask",
      "raptor mask",
      "raven mask",
      "red stocking mask",
      "reindeer mask",
      "robot human mask",
      "robot mask",
      "rooster mask",
      "samurai mask",
      "shamanic mask",
      "skeleton king mask",
      "snowboarders mask",
      "snowflake glasses",
      "snowman mask",
      "sports mask",
      "stealthy mask",
      "tied scarf mask",
      "tight mask",
      "toothy mask",
      "trending shark head hat"
    ],
    "HEADWEAR": [
      "Satanic horns"
    ],
    "WATCH": [
      "Kolex watch of type *",
      "Vasio G-Shock watch",
      "Volex watch of type *"
    ],
    "BACKPACK SKINS": [
      "ATM backpack skin",
      "Backpack from the Cubic Friend paired set skin",
      "Backpack with piggy keychain skin",
      "Branded Small backpack skin",
      "Capsule backpack skin",
      "Chain bag with spikes skin",
      "Classic Lui Vui backpack skin",
      "Cloud backpack skin",
      "Cross backpack skin",
      "Duffel Bag skin",
      "Fur-lined bunny backpack",
      "Gauard bag with Ladudu skin",
      "Gayardo shoulder bag skin",
      "Gingerbread house backpack skin",
      "Grand backpack skin",
      "HaHaHa set crossbody bag skin",
      "Happy bear shoulder bag skin",
      "LUV backpack with wings skin",
      "LV backpack with water prints skin",
      "LV crossbody bag skin",
      "LW Crossbody Bag skin",
      "LW Everyday Bag skin",
      "Large LV crossbody bag skin",
      "Luv Moscnino spiky heart backpack skin",
      "Memo Bag Ladudu skin",
      "Motosport Waist bag skin",
      "Neon Chrome handbag skin",
      "SSC Kit Bag skin",
      "Scary chicken backpack skin",
      "Skeleton cheetah plush backpack skin",
      "Small shoulder bag LW skin",
      "Sweet Sheep fur bag",
      "X Ban Lui Vui backpack skin"
    ],
    "SPATIAL SOUND EFFECTS": [
      "Aghhhhh",
      "Alien",
      "Bonk",
      "Boowomp",
      "Bro",
      "Brother eww",
      "Cartoon tickle",
      "Crickets",
      "Directed by",
      "Duck",
      "Faaah",
      "Festive whistle",
      "Goofy laugh",
      "I love you",
      "Kiss",
      "Laughter",
      "Mwahahaha",
      "No no no no wait",
      "Romantic",
      "Sad sound",
      "Sad violin",
      "Six Seven",
      "Skeleton hits a shield",
      "Suspicious",
      "Suspicious sound",
      "Toy sound",
      "Uwu",
      "Vagabond",
      "Whistle sound",
      "Woooow",
      "Yeah boy"
    ],
    "ANIMATED ITEMS": [
      "Chick",
      "Duck Blaster",
      "Earth Slime",
      "Fire Ring",
      "Lightning Charge",
      "Macaque with Pacifier",
      "Mister Seal",
      "Noodle Lover",
      "Piglet on Bread",
      "Royal Bird",
      "The Bat",
      "Toy Fish",
      "Unicorn Aura",
      "Wizard Cat"
    ]
  },
  "female": {
    "TOP/HOODIE": [
      "Branded Top esential suit",
      "Watch Me sweater",
      "bandana top",
      "collection 5 top",
      "corset top",
      "day dress",
      "dress",
      "faution top",
      "jumpsuit",
      "long brand T-shirt",
      "low dress",
      "pullover with long sleeve",
      "short pullover",
      "stylish suit",
      "summer bra",
      "top 2 outerwear",
      "top Faution",
      "top with chains",
      "winter collection dress"
    ],
    "PANTS": [
      "Abibas leggings",
      "Abibas pants",
      "Branded Bottom esential suit",
      "Custom Jeans",
      "Muci shorts",
      "jeans",
      "skirt with tights"
    ],
    "SHOES": [
      "luminous shoes",
      "tall boots"
    ],
    "ACCESSORY": [
      "navel piercing accessory"
    ],
    "HEADWEAR": [
      "rabbit ears"
    ],
    "WATCH": [
      "Kolex watch of type *",
      "Volex watch of type *"
    ],
    "Dress": [
      "Love costume",
      "Spring set S23",
      "Wedding dress",
      "luminous dress"
    ]
  }
};

// Tum erkek/kadin esyalarini tek bir aranabilir listeye duzlestirir.
// Not: Bazi isimler hem MALE hem FEMALE altinda ayni sekilde gecebilir (orn. "Abibas pants",
// "luminous shoes", "Volex watch of type *"). Bu, xlsx kaynaginda boyle tanimlanmis; UI tarafinda
// cinsiyet secimi (for men/women) ayri bir alan oldugu icin çakışma degil, kasitli tekrar.
function flatten(section) {
  const out = [];
  for (const category of Object.keys(section)) {
    for (const item of section[category]) {
      out.push({ name: item, category, });
    }
  }
  return out;
}

export const MALE_ITEMS = flatten(CLOTHING.male);
export const FEMALE_ITEMS = flatten(CLOTHING.female);

// Tekil isim listesi (arama/select icin) — kategori bilgisini kaybetmeden.
export const ALL_CLOTHING_ITEMS = (() => {
  const map = new Map();
  for (const it of [...MALE_ITEMS, ...FEMALE_ITEMS]) {
    if (!map.has(it.name)) map.set(it.name, new Set());
    map.get(it.name).add(it.category);
  }
  return Array.from(map.entries()).map(([name, categories]) => ({
    name,
    categories: Array.from(categories),
  }));
})();

export function clothingItemExists(name) {
  return ALL_CLOTHING_ITEMS.some(i => i.name.toLowerCase() === name.toLowerCase());
}
