// AUTO-GENERATED from LifeInvader (EN3) Clothing_and_Vehicle_List.xlsx — 'Vehicles' sheet
// Bu dosya elle duzenlenmemelidir. Kaynak dosya guncellenince yeniden uretilmelidir.
// Regeneration script: bkz. proje notlari / xlsx->JSON extraction script.

export const VEHICLES = {
  "sellable": [
    "9F",
    "9F Cabrio",
    "Adder",
    "Albany Escalade",
    "Alpha",
    "Annis 350Z",
    "Annis GT-R I",
    "Annis RX-7 (FD)",
    "Annis RX-7 (Veilside Fortune)",
    "Annis Silvia (S15)",
    "Annis Skyline GT-R (R34)",
    "Annis WRX 2004",
    "Annis ZR-350",
    "Apocalypse Impaler",
    "Apocalypse Imperator",
    "Apocalypse Issi",
    "Apocalypse Slamvan",
    "Ardent",
    "Asbo",
    "Asea",
    "Asterope",
    "Autarch",
    "BF Injection",
    "Baller",
    "Baller LE LWB",
    "Baller SG",
    "Banshee",
    "Banshee 900R",
    "Beater Emperor",
    "Beater Mariachi Tornado",
    "Beater Surfer",
    "Beater Tornado",
    "Benefactor-Benz 600SEL (W140)",
    "Benefactor-Benz E420 (W210)",
    "Benefactor-Benz Vito (V447)",
    "Benefactor-MG C63 (W205)",
    "Benefactor-MG C63 Coupe (W205)",
    "Benefactor-MG G63 (G770)",
    "Benefactor-MG GT",
    "Benefactor-MG S63 (W222)",
    "Benefactor-MG SL65 (R230)",
    "Benefactor-MG VT Black Series",
    "Benefactor-Maybach Pullman",
    "Bestia GTS",
    "Bison",
    "Blade",
    "Blista",
    "Blista Kanjo",
    "Bodhi",
    "Bravado Challenger 2016",
    "Bravado Charger 1969",
    "Bravado Charger SRT",
    "Bravado Ram 1500",
    "Bravado Viper 2008",
    "Brawler",
    "Brioso R/A",
    "Buccaneer",
    "Buffalo",
    "Bullet",
    "Burgerfahrzeug Golf GTI Vision",
    "Calico GTF",
    "Canis Grand Cherokee",
    "Caracara 4x4",
    "Carbonizzare",
    "Casco",
    "Cavalcade",
    "Cheburek",
    "Cheetah",
    "Cheetah Classic",
    "Chino",
    "Clique",
    "Cognoscenti",
    "Cognoscenti 55",
    "Cognoscenti Cabrio",
    "Coil Cybertruck",
    "Coil Model S",
    "Coil Model X",
    "Coil Roadster",
    "Comet",
    "Comet S2",
    "Comet SR",
    "Contender",
    "Coquette",
    "Coquette Blackfin",
    "Coquette D10",
    "Couquette Classic",
    "Cyclone",
    "Cypher",
    "Declasse Camaro 2020",
    "Declasse Corvette C7",
    "Declasse Tahoe",
    "Deveste Eight",
    "Deviant",
    "Dilettante",
    "Dinka NSX 2017",
    "Dinka RT-3000",
    "Dominator",
    "Dominator ASP",
    "Dominator GTT",
    "Dominator GTX",
    "Dominator PiBwasser",
    "Drift Yosemite",
    "Dubsta",
    "Dubsta 6x6",
    "Dubsta SG",
    "Dukes",
    "ETR-1",
    "Elegy RH8",
    "Elegy Retro Custom",
    "Ellie",
    "Emperor",
    "Emperor LX-570",
    "Emperor RCF",
    "Entity XF",
    "Enus Continental GT",
    "Enus Cullinan",
    "Enus Phantom",
    "Enus Spectre",
    "Euros",
    "Exemplar",
    "F620",
    "FMJ",
    "FQ 2",
    "Faction",
    "Felon",
    "Felon GT",
    "Feltzer",
    "Flash GT",
    "Fugitive",
    "Furore GT",
    "Fusilade",
    "Futo",
    "Futo GTX",
    "Future Shock Issi",
    "GB200",
    "GP-1",
    "GT 500",
    "Gallivanter Defender",
    "Gallivanter Defender Christmas Edition",
    "Gallivanter Defender Halloween Edition",
    "Gauntlet",
    "Gauntlet Classic",
    "Gauntlet Hellfire",
    "Gauntlet Redwood",
    "Glendale",
    "Granger",
    "Grotti Italia (F458)",
    "Growler",
    "Hermes",
    "Hotknife",
    "Huntley S",
    "Imorgon",
    "Impaler",
    "Infernus",
    "Infernus Classic",
    "Ingot",
    "Issi",
    "Itali GTB",
    "Itali GTB Custom",
    "Itali GTO",
    "JB 700",
    "Jackal",
    "Jester",
    "Jester (Racecar)",
    "Jester Classic",
    "Jester RR",
    "Journey",
    "Jugular",
    "Kamacho",
    "Karin Land Cruiser 200",
    "Karin Mark 2",
    "Karin Supra A80",
    "Karin Tundra 2021",
    "Khamelion",
    "Komoda",
    "Krieger",
    "Lampadati Giulia GTA",
    "Landstalker",
    "Lynx",
    "Mamba",
    "Mammoth HUM EV",
    "Massacro",
    "Monowheel",
    "Monroe",
    "Moonbeam",
    "Nebula Turbo",
    "Neon",
    "Nero",
    "Nero Custom",
    "Nightshade",
    "Novak",
    "Obey A6",
    "Obey A8",
    "Obey Q8",
    "Obey R8",
    "Obey RS6",
    "Obey RS7",
    "Obey S8 (D4)",
    "Ocelot Eletre",
    "Ocelot F-Type R",
    "Ocelot Vanquish Zagto SB",
    "Ocelot Victor",
    "Oracle",
    "Osiris",
    "Panto",
    "Paragon R",
    "Pariah",
    "Patriot",
    "Patriot Stretch",
    "Pegassi Huayra BC",
    "Pegassi Performante (LP640)",
    "Penetrator",
    "Penumbra",
    "Peyote Gasser",
    "Pfister 811",
    "Pfister 918 Spyder",
    "Pfister Panamera",
    "Pfister Taycan",
    "Pheonix",
    "Picador",
    "Prairie",
    "Premier",
    "Previon",
    "Progen 675 LT",
    "RE-7B",
    "Raiden",
    "Rancher XL",
    "Rapid GT",
    "Raptor",
    "Rat-Loader",
    "Rat-Truck",
    "Reaper",
    "Rebel",
    "Rebla GTS",
    "Regina",
    "Remus",
    "Revolter",
    "Rhapsody",
    "Riata",
    "Rocoto",
    "Ruiner",
    "Rumpo",
    "Ruston",
    "Rusty Rebel",
    "SC-1",
    "Sabre Turbo",
    "Sandking SWB",
    "Sandking XL",
    "Schafter",
    "Schafter LWB",
    "Schafter LWB (Armored)",
    "Schafter V12",
    "Schlagen GT",
    "Schwarzer",
    "Seminole",
    "Sentinel Classic",
    "Sentinel XS",
    "Serrano",
    "Seven-70",
    "Shelby GT500",
    "Slam Van",
    "Slamvan Custom",
    "Specter",
    "Stafford",
    "Stallion",
    "Stinger",
    "Stinger GT",
    "Stirling GT",
    "Streiter",
    "Stretch",
    "Sultan",
    "Sultan Classic",
    "Sultan RS",
    "Sultan RS Classic",
    "Super Diamond",
    "Surano",
    "Surge",
    "Swinger",
    "T-20",
    "Tailgater",
    "Tailgater S",
    "Taipan",
    "Tampa",
    "Tempesta",
    "Tezeract",
    "Thrax",
    "Tigon",
    "Torero",
    "Toros",
    "Tropos Rallye",
    "Truffade Centodieci",
    "Truffade Chiron",
    "Tulip",
    "Turismo Classic",
    "Turismo R",
    "Tyrant",
    "Tyrus",
    "Ubermacht 760 (LI)",
    "Ubermacht I8",
    "Ubermacht M3 (E46)",
    "Ubermacht M3 (G80)",
    "Ubermacht M4 (G82)",
    "Ubermacht M4 (GTS)",
    "Ubermacht M5 (CS)",
    "Ubermacht M5 (CS) Halloween Edition",
    "Ubermacht M5 (E34)",
    "Ubermacht M5 (E60)",
    "Ubermacht M8 (F91)",
    "Ubermacht X5 (E70)",
    "Ubermacht X5 (G05)",
    "Ubermacht X6-M (E71)",
    "Ubermacht X7 (G07)",
    "V-STR",
    "Vacca",
    "Vagner",
    "Vamos",
    "Vectre",
    "Velierer",
    "Vigero",
    "Virgo",
    "Virgo Classic",
    "Viseris",
    "Visione",
    "Voltic",
    "Voodoo",
    "Voodoo Custom",
    "Warrener",
    "Warrener HKR",
    "Washington",
    "Windsor",
    "Windsor Drop",
    "X80 Proto",
    "XA-21",
    "XLS",
    "XLS (Armored)",
    "Yosemite",
    "Yosemite Rancher",
    "Z-Type",
    "Zentorno",
    "Zion",
    "Zion Cabrio",
    "Zion Classic",
    "Zorrusso"
  ],
  "notSellable": [
    "Annis Concept 2021",
    "Benefactor-Benz 190E (Evolution II)",
    "Benefactor-Benz 300 SL (W198)",
    "Benefactor-Benz GLC300",
    "Benefactor-Benz GLS 63",
    "Benefactor-Benz MG Visione",
    "Benefactor-Benz Vision AVTR",
    "Benefactor-MG A45 (W176)",
    "Benefactor-MG CLS53 (C257)",
    "Benefactor-MG E63 (W213)",
    "Benefactor-MG G63 (6X6)",
    "Benefactor-MG GLE63 Coupe",
    "Benefactor-MG Project One",
    "Benefactor-Maybach GLS600",
    "Benefactor-Maybach S63 (W223)",
    "Brabus Rocket G900",
    "Bravado Charger Daytona",
    "Enus EXP 10",
    "Enus Wraith",
    "Gallivanter Evoque",
    "Genesis G90",
    "Grotti FXX-K Evo",
    "Grotti Monza (SP2)",
    "Grotti Pista (F488)",
    "Grotti Stradale (SF90)",
    "Grotti Superfast (F812)",
    "Grotti Tributo (F8)",
    "KMTA Optima",
    "Karin Corolla AE",
    "Obey E-Tron Sportback",
    "Obey RS E-Tron GT",
    "Obey RS5 Coupe",
    "Obey TT",
    "Ocelot Evora",
    "Ocelot GranTurismo",
    "Ocelot Vulcan",
    "Overflod CCX",
    "Overflod Gemera",
    "Overflod Jesko 2020",
    "Overflod One",
    "Overflod Regera",
    "Pegassi Alston (SC18)",
    "Pegassi Aventador (LP700)",
    "Pegassi Centenario (LP770)",
    "Pegassi Countach (LP400)",
    "Pegassi Countach (LPI 800-4)",
    "Pegassi Diablo (SV)",
    "Pegassi Reventon",
    "Pegassi SE (PJ1)",
    "Pegassi Sian",
    "Pegassi Terzo",
    "Pegassi Urus",
    "Pegassi Veneno (LP750)",
    "Pfister 911 Turbo 2021",
    "Pfister Cayenne",
    "Pfister Panamera Turismo",
    "Progen 765 LT (Spider)",
    "Progen Elva",
    "Progen P1",
    "SSC Tuatara",
    "Shelby Cobra Daytona",
    "Skoda Octavia RS",
    "Truffade Bolide",
    "Truffade Divo",
    "Truffade La Voiture Noire",
    "Truffade Veyron",
    "Ubermacht M5 (F90)",
    "Ubermacht Vision",
    "Ubermacht Z4 (E85)",
    "Vapid Focus RS",
    "Vapid GT 2017",
    "Vapid Mustang 1965",
    "Vapid Mustang MACH-E",
    "Vapid Raptor F150"
  ],
  "motorcycles": [
    "Akuma",
    "Apocalypse Deathbike",
    "Avarus",
    "BF-400",
    "BMX",
    "Bagger",
    "Bati 801",
    "Bati 801RR",
    "Blazer",
    "Blazer Lifeguard",
    "Carbon RS",
    "Chimera",
    "Cliffhanger",
    "Cruiser",
    "Daemon",
    "Defiler",
    "Diabolus",
    "Diabolus Custom",
    "Double-T",
    "Enduro",
    "Esskey",
    "FCR 1000",
    "FCR 1000 Custom",
    "Faggio",
    "Future Shock Deathbike",
    "Gargoyle",
    "Hakuchou",
    "Hakuchou Drag",
    "Hexer",
    "Innovation",
    "Lectro",
    "Manchez",
    "Nemesis",
    "Nightblade",
    "PCJ-600",
    "Rat Bike",
    "Ruffian",
    "Sanchez",
    "Sanctus",
    "Shotaro",
    "Sovereign",
    "Street Blazer",
    "Stryder",
    "Thrust",
    "Tri-Cycles Race Bike",
    "Vader",
    "Vindicator",
    "Vortex",
    "Whippet Race Bike",
    "Wolfsbane",
    "Zombie Chopper"
  ],
  "boats": [
    "Dinghy",
    "Dinghy (2-Seater)",
    "Dinghy (Yacht)",
    "Jetmax",
    "Marquis",
    "SeaShark",
    "Speeder",
    "Squalo",
    "Suntrap",
    "Toro",
    "Tropic"
  ],
  "planes": [
    "Alpha-Z1",
    "Cuban 800",
    "Dodo",
    "Duster",
    "Howard NX-25",
    "Luxor",
    "Luxor Deluxe",
    "Malard",
    "Mammatus",
    "Microlight",
    "Nimbus",
    "P-45 Nokota",
    "V-65 Molotok",
    "Velum"
  ],
  "helicopters": [
    "Buzzard",
    "Frogger",
    "Maverick",
    "Sparrow",
    "SuperVolito Carbon",
    "Swift Deluxe",
    "Volatus"
  ]
};

// Yardimci fonksiyonlar
export const ALL_SELLABLE = [
  ...VEHICLES.sellable,
  ...VEHICLES.motorcycles,
  ...VEHICLES.boats,
  ...VEHICLES.planes,
  ...VEHICLES.helicopters,
];

export const ALL_VEHICLES = [...ALL_SELLABLE, ...VEHICLES.notSellable];

// Bir aracin normal Sell/Buy/Trade islemine izinli olup olmadigini kontrol eder.
// "NOT SELLABLE CARS" listesindeki araclar sadece kiralanabilir/kiraya verilebilir.
export function isSellable(vehicleName) {
  return VEHICLES.sellable.includes(vehicleName)
    || VEHICLES.motorcycles.includes(vehicleName)
    || VEHICLES.boats.includes(vehicleName)
    || VEHICLES.planes.includes(vehicleName)
    || VEHICLES.helicopters.includes(vehicleName);
}

export function isRentOnly(vehicleName) {
  return VEHICLES.notSellable.includes(vehicleName);
}

export function vehicleExists(vehicleName) {
  return ALL_VEHICLES.includes(vehicleName);
}
